version: "3.1"

services:
  db:
    image: postgres:13.1
    privileged: true
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: zap
      POSTGRES_PASSWORD: zap123456
      POSTGRES_DB: todo
  backend:
    build: ./todo
    privileged: true
    expose:
      - 8080
    command: bash -c "python manage.py migrate &&
      python manage.py fill_db &&
      gunicorn todo.wsgi -b 0.0.0.0:8080"
    depends_on:
      - db
  nginx:
    build: ./nginx
    ports:
      - 8000:80
    depends_on:
      - backend
  frontend:
    build: ./frontend
    ports:
      - 80:80
    depends_on:
      - nginx
